# H2 Database Configuration
# to view the database content at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:cinemadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'create-drop' is good for prototypes; it creates the schema on startup and drops it on shutdown
spring.jpa.hibernate.ddl-auto=create-drop